name: Deploy

on:
  push:
    branches:
      - main

env:
  ADMIN_PASS: ${{ secrets.ADMIN_PASS }}

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker compose up
        run: |
          docker compose up --build -d